name: "Prepare infra meeting notes as release"

on:
  workflow_dispatch:
    inputs:
      milestone_id:
        description: '"Current" milestone id to prepare as release'
        required: true
        # TODO: set a default value via another GHA retrieving the last milestone opened
        type: string
      milestone_name:
        description: '"Current" milestone name'
        required: true
        default: 'current'
        type: string
      next_milestone_id:
        description: '"Next" milestone id'
        required: true
        default: '4'
        type: string
      next_milestone_name:
        description: '"Next" milestone name'
        required: true
        default: 'next'
        type: string

jobs:
  release:
    name: "Prepare infra meeting notes as release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Generate markdown from current and next milestone"
        id: milestones_as_markdown
        uses: "actions/github-script@v6"
        with:
          result-encoding: string
          script: |
            const getMilestoneAsMarkdown = async function(milestone, milestoneName) {
              const opts = github.rest.issues.listForRepo.endpoint.merge({
                ...context.issue,
                milestone,
                state: 'all'
              })
              const issues = await github.paginate(opts)

              let closedIssues = []
              let openIssues = []
              for (const issue of issues) {
                if (issue.state == 'closed') {
                  closedIssues.push(issue)
                } else {
                  openIssues.push(issue)
                }
              }

              let markdown = ''

              if (closedIssues.length > 0) {
                markdown = `* [Done](${context.payload.repository.html_url}/milestone/${milestone}?closed=1):`
                for (const issue of closedIssues) {
                  markdown = markdown.concat("\r\n").concat(`  * [${issue.title}](${issue.html_url})`)
                }
              }

              if (openIssues.length > 0) {
                issueType = (milestoneName != 'next') ? 'Work In Progress' : 'New/Important'
                spacer = (markdown != '' && milestoneName != 'next') ? "\r\n\r\n" : ''
                markdown = markdown.concat(spacer)
                  .concat(`* [${issueType}](${context.payload.repository.html_url}/milestone/${milestone}):`)
                for (const issue of openIssues) {
                  markdown = markdown.concat("\r\n").concat(`  * [${issue.title}](${issue.html_url})`)
                }
              }

              return markdown
            }

            current = await getMilestoneAsMarkdown(context.payload.inputs.milestone_id, context.payload.inputs.milestone_name)
            next = await getMilestoneAsMarkdown(context.payload.inputs.next_milestone_id, context.payload.inputs.next_milestone_name)

            return `Markdown for the infra team sync meeting notes preparation:
            <pre>
            ${current}

            ${next}
            </pre>

            <details><summary>Preview:</summary>

            ${current}

            ${next}

            </details>
            `

      - name: "Get current date"
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: "Create release"
        id: create_release
        uses: "actions/github-script@v6"
        env:
          CURRENT_DATE: ${{ steps.date.outputs.date }}
          RELEASE_BODY: ${{steps.milestones_as_markdown.outputs.result}}
        with:
          script: |
            name = `infra-team-sync-${process.env.CURRENT_DATE}`
            tag = `${name}_${context.runNumber}`

            try {
              await github.rest.repos.createRelease({
                name: name,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: process.env.RELEASE_BODY,
                tag_name: tag,
                draft: true,
                generate_release_notes: true,
                prerelease: false,
                // This doesn't work if draft: true, to be added via gha on release publication (+milestone closing/creation?)
                discussion_category_name: 'General',
              });
            } catch (error) {
              core.setFailed(error.message);
            }
