name: "Prepare infra meeting notes as release"

on:
  workflow_dispatch:
    inputs:
      milestone_id:
        description: '"Current" milestone id to prepare as release'
        required: true
        # TODO: set a default value via another GHA retrieving the last milestone opened
        type: string
      milestone_name:
        description: '"Current" milestone name'
        required: true
        default: 'current'
        type: string
      next_milestone_id:
        description: '"Next" milestone id'
        required: true
        default: '4'
        type: string
      next_milestone_name:
        description: '"Next" milestone name'
        required: true
        default: 'next'
        type: string

jobs:
  release:
    name: "Prepare infra meeting notes as release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Gather release body"
        id: gather_release_body
        uses: "actions/github-script@v6"
        with:
          result-encoding: string
          script: |
            const getMilestoneAsMarkdown = async function(milestone, milestoneName) {
              const opts = github.rest.issues.listForRepo.endpoint.merge({
                ...context.issue,
                milestone,
                state: 'all'
              })
              const issues = await github.paginate(opts)

              let closedIssues = []
              let openIssues = []
              for (const issue of issues) {
                if (issue.state == 'closed') {
                  closedIssues.push(issue)
                } else {
                  openIssues.push(issue)
                }
              }

              let body = ''
              
              if (closedIssues.length > 0) {
                body = `* [Done](${context.payload.repository.html_url}/milestone/${milestone}?closed=1):`
                for (const issue of closedIssues) {
                  body = body.concat("\r\n").concat(`  * [${issue.title}](${issue.html_url})`)
                }
              }

              if (openIssues.length > 0) {
                issueType = (milestoneName != 'next') ? 'Work In Progress' : 'New/Important'
                spacer = (body != '' && milestoneName != 'next') ? "\r\n\r\n" : ''
                body = body.concat(spacer)
                  .concat(`* [${issueType}](${context.payload.repository.html_url}/milestone/${milestone}):`)
                for (const issue of openIssues) {
                  body = body.concat("\r\n").concat(`  * [${issue.title}](${issue.html_url})`)
                }
              }

              return body
            }

            // Retrieve the markdown content related to the "current" milestone issues
            bodyCurrent = await getMilestoneAsMarkdown(context.payload.inputs.milestone_id, context.payload.inputs.milestone_name)
            
            // Retrieve the markdown content related to the "next" milestone issues
            bodyNext = await getMilestoneAsMarkdown(context.payload.inputs.next_milestone_id, context.payload.inputs.next_milestone_name)
            
            releaseBody = `Markdown for the infra team sync meeting notes preparation:
            <pre>
            ${bodyCurrent}

            ${bodyNext}
            </pre>
            
            <details><summary>Preview:</summary>

            ${bodyCurrent}

            ${bodyNext}

            </details>
            `

            return releaseBody

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: "Create release"
        id: create_release
        uses: "actions/github-script@v6"
        env:
          CURRENT_DATE: ${{ steps.date.outputs.date }}
          RELEASE_BODY: ${{steps.gather_release_body.outputs.result}}
        with:
          script: |
            releaseName = `infra-team-sync-${process.env.CURRENT_DATE}`

            // Create the (draft) release with the content retrieved in earlier step
            try {
              await github.rest.repos.createRelease({
                draft: true,
                generate_release_notes: true,
                name: releaseName,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: releaseName,
                body: process.env.RELEASE_BODY,
                // This doesn't work if draft: true, to be added via gha on release publication (+milestone closing/creation?)
                discussion_category_name: 'General',
              });
            } catch (error) {
              core.setFailed(error.message);
            }
