name: "Prepare infra meeting notes release"

# https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
on:
  workflow_dispatch:
    inputs:
      milestone_id:
        description: 'Milestone id to prepare for release'
        required: true
        default: '1'
        type: string
      milestone_name:
        description: 'Milestone name'
        required: true
        default: 'current'
        type: string
      next_milestone_id:
        description: '"Next" milestone id'
        required: true
        default: '4'
        type: string
      next_milestone_name:
        description: '"Next" milestone name'
        required: true
        default: 'next'
        type: string


jobs:
  release:
    name: "Prepare infra meeting notes release"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Gather release body"
        id: gather_release_body
        uses: "actions/github-script@v6"
        with:
          result-encoding: string
          script: |
            const getMilestoneIssuesAsMarkdown = async function(milestone, milestoneName) {
            console.log(`milestone: ${milestone}, milestoneName: ${milestoneName}`)
              const opts = github.rest.issues.listForRepo.endpoint.merge({
                ...context.issue,
                milestone,
                state: 'all'
              })
              const issues = await github.paginate(opts)

              let closedIssues = []
              let openIssues = []
              for (const issue of issues) {
                if (issue.state == 'closed') {
                  console.log(`issue ${issue.html_url} closed`)
                  closedIssues.push(issue)
                } else {
                  console.log(`issue ${issue.html_url} not closed (${issue.state})`)
                  openIssues.push(issue)
                }
              }
              let returnedBody = ''
              
              if (closedIssues.length > 0) returnedBody = returnedBody.concat("\r\n\r\n").concat(`## Closed issues in [${milestoneName} milestone](${context.payload.repository.html_url}/milestones/${milestone}):`)
              for (const issue of closedIssues) {
                returnedBody = returnedBody.concat("\r\n").concat(`  * [${issue.title}](${issue.html_url})`)
              }
              
              if (openIssues.length > 0) returnedBody = returnedBody.concat("\r\n\r\n").concat(`## Open issues in [${milestoneName} milestone](${context.payload.repository.html_url}/milestones/${milestone}):`)
              for (const issue of openIssues) {
                returnedBody = returnedBody.concat("\r\n").concat(`  * [${issue.title}](${issue.html_url})`)
              }
              
              return returnedBody
            }

            releaseBodyCurrent = await getMilestoneIssuesAsMarkdown(context.payload.inputs.milestone_id, context.payload.inputs.milestone_name)
            releaseBodyNext = await getMilestoneIssuesAsMarkdown(context.payload.inputs.next_milestone_id, context.payload.inputs.next_milestone_name)
            
            releaseBodyCurrentAndNext = releaseBodyCurrent.concat("\r\n\r\n")
              .concat('---')
              .concat(releaseBodyNext)
            
            releaseBody = releaseBodyCurrentAndNext.concat("\r\n")
              .concat('<details><summary>Markdown:</summary>')
              .concat("\r\n")
              .concat('<pre>')
              .concat(releaseBodyCurrentAndNext)
              .concat("\r\n")
              .concat('</pre>')
              .concat("\r\n")
              .concat('</detail>')

            // or

            releaseBody = 'Markdown:'.concat("\r\n")
              .concat("\r\n")
              .concat('<pre>')
              .concat(releaseBodyCurrentAndNext)
              .concat("\r\n")
              .concat('</pre>')
              .concat("\r\n")
              .concat('<details><summary>Preview:</summary>')
              .concat("\r\n")
              .concat(releaseBodyCurrentAndNext)
              .concat("\r\n")
              .concat('</detail>')

            console.log('releaseBody:')
            console.log(releaseBody)
            return releaseBody
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create tag
        id: create_tag
        uses: actions/github-script@v6
        env:
          CURRENT_DATE: ${{ steps.date.outputs.date }}
        with:
          script: |
            const tagName = `infra-team-sync-${process.env.CURRENT_DATE}_${context.runNumber}`
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tagName}`,
              sha: context.sha
            })
            console.log(tagName)
            return tagName
      - name: "Create release"
        uses: "actions/github-script@v6"
        env:
          RELEASE_TAG: ${{steps.create_tag.outputs.result}}
          RELEASE_BODY: ${{steps.gather_release_body.outputs.result}}
        with:
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: true,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
                body: process.env.RELEASE_BODY,
              });
            } catch (error) {
              core.setFailed(error.message);
            }
